config/routes.rb
Dairy::Application.routes.draw do

  resources :dairys
   root 'dairys#new'
   

end

app/models/dairy_app.rb
class DairyApp < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dairys_controller.rb
class DairysController < ApplicationController
	def index
		@dairy_posts = DairyApp.all
	end
	
	def new
		@dairy = DairyApp.new
	end
	
	def show
		@dairy_posts = DairyApp.find(params[:id])
	end
	
	def edit
		@dairy_posts = DairyApp.find(params[:id])
	end
	
	def create
		@dairy_posts = DairyApp.new(new_entry)
		@dairy_posts.save
		redirect_to action: 'index'
	end
	
	def destroy
		@dairy_posts = DairyApp.find(params[:id])
		@dairy_posts.destroy
		redirect_to dairys_path
	end
	
	private
		def new_entry
			params.require(:dairy_app).permit(:timestamp, :text)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dairys_helper.rb
module DairysHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dairys/edit.html.erb
<%= form_for :dairy_posts, url: dairy_path(@dairy_posts), method: :patch do |e| %>
	<p>
		<%= e.text_area :text %>
	</p>
	
	<p>
		<%= e.submit %>
<% end %>
<br><br>
<p><%= link_to 'Back', dairys_path %></p>

app/views/dairys/index.html.erb
<%= link_to 'Write Post', new_dairy_path %><br><br>

<table>
<% @dairy_posts.each do |entry| %>
<tr>
<td><%= entry.id %> </td>
<td><%= entry.timestamp %> </td>
<td><%= entry.text %> </td>
<td><%= link_to 'Show', dairy_path(entry) %> </td>
<td><%= link_to 'Edit', edit_dairy_path(entry) %> </td>
<td><%= link_to 'Destroy', dairy_path(entry), method: :delete, data: 
{ confirm: 'Are you sure?' } %> </td>
<% end %>
</tr>
</table>

app/views/dairys/new.html.erb
<%= form_for(@dairy, url: dairys_path) do |f| %>
 
  <p>
    <%= f.text_area :text %>
    <%= f.hidden_field :timestamp, value: Time.now.to_s %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/dairys/show.html.erb
<table>
<tr>
<td><%= @dairy_posts.text %> </td>
</tr>
</table><br><br>
<p><%= link_to 'Back', dairys_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dairy</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>My Dairy</h1>